artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1CFpSm2eOqg40RRehMeeowFf_DQCDqlT-/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  real_process_imgs: artifacts/data_ingestion/real
  fack_process_imgs: artifacts/data_ingestion/fack
  
data_preprocessing:
  root_dir: artifacts/data_preprocessing
  unzip_dir_real: artifacts/data_ingestion/Norpeat liveness dataset/real
  unzip_dir_fake: artifacts/data_ingestion/Norpeat liveness dataset/fake
  real_process_imgs: artifacts/data_preprocessing/real
  fake_process_imgs: artifacts/data_preprocessing/fake

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5